//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualReadingopration.dbo_connt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualReading
    {
        public int SiteId { get; set; }
        public string DataBaseName { get; set; }
        public string MeterId { get; set; }
        public Nullable<double> MainReading { get; set; }
        public Nullable<double> DG_reading { get; set; }
        public string Engineer_Name { get; set; }
        public string joiningdate { get; set; }
    }
}
